### ISSUE TITLE
Check whether `ContextAwareCompletableFutureTest` is flaky

### ISSUE THREAD

**Issue by sjoerdtalsma** [talsma-ict/context-propagation#499]
A bit unrelated, but is `ContextAwareCompletableFutureTest` flaky?
In my fork I just got a test failure there:

<details>

<summary>Test failure (click to expand)</summary>

https://github.com/Marcono1234/context-propagation/actions/runs/11245200679/job/31264757917#step:8:663

```
 Error:  Tests run: 82, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.202 s <<< FAILURE! -- in nl.talsmasoftware.context.futures.ContextAwareCompletableFutureTest
Error:  nl.talsmasoftware.context.futures.ContextAwareCompletableFutureTest.testRunAfterEitherAsyncAndTakeNewSnapshot -- Time elapsed: 0.010 s <<< ERROR!
java.util.concurrent.ExecutionException: 
java.lang.AssertionError: 
Expected: a string starting with "-"
     but: was "Glass of beer"
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at nl.talsmasoftware.context.futures.ContextAwareCompletableFutureTest.testRunAfterEitherAsyncAndTakeNewSnapshot(ContextAwareCompletableFutureTest.java:1816)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
Caused by: java.lang.AssertionError: 
Expected: a string starting with "-"
     but: was "Glass of beer"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at nl.talsmasoftware.context.futures.ContextAwareCompletableFutureTest.lambda$testRunAfterEitherAsyncAndTakeNewSnapshot$356(ContextAwareCompletableFutureTest.java:1815)
	at nl.talsmasoftware.context.functions.ConsumerWithContext.accept(ConsumerWithContext.java:55)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at nl.talsmasoftware.context.futures.ContextAwareCompletableFuture.lambda$wrap$0(ContextAwareCompletableFuture.java:478)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:575)
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:1068)
	at java.util.concurrent.CompletableFuture$OrRun.tryFire(CompletableFuture.java:1495)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

</details>

Maybe the use of `runAfterEitherAsync` (and also the other `either` methods) creates a race condition there, where the first `initializeNewContext` call is actually executed _second_?
(might affect multiple test methods)

_Originally posted by @Marcono1234 in https://github.com/talsma-ict/context-propagation/issues/498#issuecomment-2400986419_

**Comment by Marcono1234** [comment]
Some more information:
- It looks like this occurred for JDK 8:
  ```
  Toolchain in maven-surefire-plugin: JDK[/opt/hostedtoolcache/Java_Zulu_jdk/8.0.422-5/x64]
  ```
- The commit where this happened is roughly equivalent to 29390503e35760f3f84123bb6756151e0e95d3df
- Full log file: [job-logs.txt](https://github.com/user-attachments/files/17318500/job-logs.txt)

I am adding this here because I will delete the action run (respectively my fork), and I think the log file would otherwise be deleted by GitHub at some point anyway.

Though most likely the information above won't be that useful for reproducing, if this is really a race condition.
